from . import ordertech_configration
from . import res_company
from . import res_partner
from . import product_template
from . import pos_category
from . import product_attribute
from . import product_attribute_value
from . import pos_order
from . import preparation_display_order